//
//  SearchPresenter.swift
//  MusicApp
//
//  Created by Сергей Иванов on 06.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic
{
    func presentSomething(response: Search.Something.Response.ResponseType)
}

class SearchPresenter: SearchPresentationLogic
{
  weak var viewController: SearchDisplayLogic?
  
  // MARK: Do something
  
    func presentSomething(response: Search.Something.Response.ResponseType)
  {

        switch response {
        case .normalizeTracks(let searchResponse):
            let viewModel = Search.Something.ViewModel.ViewModelType.presentTracks(tracks: searchResponse?.results ?? [])
            viewController?.displaySomething(viewModel: viewModel)
        }
  }
}
