//
//  SearchInteractor.swift
//  MusicApp
//
//  Created by Сергей Иванов on 06.01.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchBusinessLogic
{
    func doSomething(request: Search.Something.Request.RequestType)
}

protocol SearchDataStore
{
    //var name: String { get set }
}

class SearchInteractor: SearchBusinessLogic, SearchDataStore
{
    var presenter: SearchPresentationLogic?
    var worker: SearchWorker?
    let networkService = Network()
    
    // MARK: Do something
    
    func doSomething(request: Search.Something.Request.RequestType)
    {
        worker = SearchWorker()
        worker?.doSomeWork()
        
        switch request {
        case .getTracks(let searchText):
            fetchRequest(searchText: searchText)
            break
        }
    }
    
    func fetchRequest(searchText: String) {
        networkService.fetchTracks(searchText: searchText) { [weak self] searchResponse in
            let response = Search.Something.Response.ResponseType.normalizeTracks(searchResponse: searchResponse)
            self?.presenter?.presentSomething(response: response)
        }
    }
    
    
}
